Add add_boxed to PlotUi.
emilk/egui_plot pull request #51
Opened 2024-10-04 23:37 UTC by freeformstu

* Closes <https://github.com/emilk/egui_plot/issues/THE_RELEVANT_ISSUE>
* [ ] I have followed the instructions in the PR template

2024-12-04 20:31 UTC, bircni requested changes

2024-12-04 20:31 UTC, bircni commented on egui_plot/src/plot_ui.rs
> +    /// Add an arbitrary item.
A test for that or an example would be nice

2024-12-17 08:02 UTC, emilk approved these changes

2024-12-17 08:02 UTC, emilk commented on egui_plot/src/plot_ui.rs
> +    pub fn add_boxed(&mut self, item: Box<dyn PlotItem>) {
```suggestion
    pub fn add_item(&mut self, item: Box<dyn PlotItem>) {
```

2024-12-17 08:11 UTC, merged